"""API pública del sistema Elo causal por género y superficie."""

from .build import (
    EloBuildReport,
    GenderBuildAudit,
    build_elo_database,
    iter_manifest_match_frames,
    load_verified_manifest,
    prepare_manifest_event_frame,
)
from .engine import (
    EXCLUDED_LEVELS,
    SURFACES,
    DateBlockError,
    EloEngine,
    EloEngineError,
)
from .events import (
    EventColumns,
    EventValidationError,
    UnknownSurfaceError,
    events_from_dataframe,
    normalise_surface,
)
from .parameters import (
    ALGORITHM_VERSION,
    DEFAULT_ELO_PARAMETERS,
    EloParameters,
)
from .operational import (
    EloHandoffConfig,
    ExplorerLoadResult,
    ExplorerOperationalResult,
    OperationalEloError,
    OperationalEloOverlay,
    OperationalOmission,
    OperationalSourceAudit,
    assemble_operational_overlay,
    build_operational_elo_overlay,
    build_operational_elo_overlay_with_fallback,
    load_elo_handoff_config,
    load_explorer_operational_results,
    publish_operational_omissions,
)
from .service import EloQuery, get_elo, get_elos
from .store import EloStore, EloStoreError, EloValidationError
from .types import (
    AuditCounts,
    DateBlockResult,
    EloRunResult,
    EloSnapshot,
    EventDecision,
    EventProvenance,
    ExclusionReason,
    Gender,
    MatchEvent,
    PlayerEloState,
    PlayerPreMatchRating,
    PreviewBlockResult,
    RatedMatch,
    Surface,
)


__all__ = [
    "ALGORITHM_VERSION",
    "AuditCounts",
    "DEFAULT_ELO_PARAMETERS",
    "DateBlockError",
    "DateBlockResult",
    "EXCLUDED_LEVELS",
    "EloBuildReport",
    "EloEngine",
    "EloEngineError",
    "EloHandoffConfig",
    "EloParameters",
    "EloQuery",
    "EloRunResult",
    "EloSnapshot",
    "EloStore",
    "EloStoreError",
    "EloValidationError",
    "EventColumns",
    "EventDecision",
    "EventProvenance",
    "EventValidationError",
    "ExplorerLoadResult",
    "ExplorerOperationalResult",
    "ExclusionReason",
    "Gender",
    "GenderBuildAudit",
    "MatchEvent",
    "OperationalEloError",
    "OperationalEloOverlay",
    "OperationalOmission",
    "OperationalSourceAudit",
    "PlayerEloState",
    "PlayerPreMatchRating",
    "PreviewBlockResult",
    "RatedMatch",
    "SURFACES",
    "Surface",
    "UnknownSurfaceError",
    "events_from_dataframe",
    "assemble_operational_overlay",
    "build_operational_elo_overlay",
    "build_operational_elo_overlay_with_fallback",
    "build_elo_database",
    "get_elo",
    "get_elos",
    "iter_manifest_match_frames",
    "load_verified_manifest",
    "load_elo_handoff_config",
    "load_explorer_operational_results",
    "normalise_surface",
    "prepare_manifest_event_frame",
    "publish_operational_omissions",
]
