# Cache durations in hours for different data types
CACHE_HOURS_NEWS = 24
CACHE_HOURS_MATCHES = 1
CACHE_HOURS_RESULTS = 1
CACHE_HOURS_TEAMS = 24
CACHE_HOURS_PLAYERS = 24
CACHE_HOURS_RANKINGS = 12
CACHE_HOURS_UPCOMING_MATCHES = 1
CACHE_HOURS_TEAM_MATCHES = 1
CACHE_HOURS_BIG_RESULTS = 1
CACHE_HOURS_PLAYER_STATS = 24